name: Build and Deploy Jekyll to gh-pages

on:
  push:
    branches:
      - main # `main` 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # 필요한 Ruby 버전

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }} # GitHub 인증 토큰
          publish_branch: gh-pages                  # 배포할 브랜치
          publish_dir: ./_site                      # 배포할 디렉토리
